Update bootstrap

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -8,35 +8,19 @@ DOTFILES_ROOT=$(pwd -P)
 set -e
 
 echo ''
+RESET=tput(sgr0)  #\033[0m
 
-info () {
-  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
-}
-
-user () {
-  printf "\r  [ \033[0;33m??\033[0m ] $1\n"
-}
-
-success () {
-  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
-}
-
-fail () {
-  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
-  echo ''
-  exit
-}
+info () { printf "\r  [ \033[00;34m..${RESET} ] $1\n" }
+user () { printf "\r  [ \033[0;33m??${RESET} ] $1\n" }
+success () { printf "\r\033[2K  [ \033[00;32mOK${RESET} ] $1\n" }
+fail () { printf "\r\033[2K  [\033[0;31mFAIL${RESET} $1\n\n"; exit }
 
 setup_gitconfig () {
-  if ! [ -f git/gitconfig.local.symlink ]
-  then
+  if ! [ -f git/gitconfig.local.symlink ]; then
     info 'setup gitconfig'
 
     git_credential='cache'
-    if [ "$(uname -s)" == "Darwin" ]
-    then
-      git_credential='osxkeychain'
-    fi
+    if [ "$(uname -s)" == "Darwin" ]; then git_credential='osxkeychain'; fi
 
     user ' - What is your github author name?'
     read -e git_authorname
@@ -56,72 +40,42 @@ link_file () {
   local overwrite= backup= skip=
   local action=
 
-  if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]
-  then
-
-    if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
-    then
-
-      local currentSrc="$(readlink $dst)"
-
-      if [ "$currentSrc" == "$src" ]
-      then
-
-        skip=true;
-
+  if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]; 
+  then if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
+    then local currentSrc="$(readlink $dst)"
+      if [ "$currentSrc" == "$src" ]; 
+      then skip=true;
       else
-
         user "File already exists: $dst ($(basename "$src")), what do you want to do?\n\
         [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
         read -n 1 action
 
         case "$action" in
-          o )
-            overwrite=true;;
-          O )
-            overwrite_all=true;;
-          b )
-            backup=true;;
-          B )
-            backup_all=true;;
-          s )
-            skip=true;;
-          S )
-            skip_all=true;;
-          * )
-            ;;
+          o ) overwrite=true;;
+          O ) overwrite_all=true;;
+          b ) backup=true;;
+          B ) backup_all=true;;
+          s ) skip=true;;
+          S ) skip_all=true;;
+          * ) ;;
         esac
-
       fi
-
     fi
 
     overwrite=${overwrite:-$overwrite_all}
     backup=${backup:-$backup_all}
     skip=${skip:-$skip_all}
 
-    if [ "$overwrite" == "true" ]
-    then
-      rm -rf "$dst"
-      success "removed $dst"
+    if [ "$overwrite" == "true" ]; 
+    then rm -rf "$dst"; success "removed $dst";
     fi
-
-    if [ "$backup" == "true" ]
-    then
-      mv "$dst" "${dst}.backup"
-      success "moved $dst to ${dst}.backup"
+    if [ "$backup" == "true" ]; 
+    then mv "$dst" "${dst}.backup"; success "moved $dst to ${dst}.backup";
     fi
-
-    if [ "$skip" == "true" ]
-    then
-      success "skipped $src"
+    if [ "$skip" == "true" ]; then success "skipped $src"; 
+    else  # "$skip !="true" <--> $skip == "false" or empty
+      ln -s "$1" "$2"; success "linked $1 to $2"
     fi
-  fi
-
-  if [ "$skip" != "true" ]  # "false" or empty
-  then
-    ln -s "$1" "$2"
-    success "linked $1 to $2"
   fi
 }
 
@@ -148,10 +102,8 @@ if [ "$(uname -s)" == "Darwin" ]
 then
   info "installing dependencies"
   if source bin/dot | while read -r data; do info "$data"; done
-  then
-    success "dependencies installed"
-  else
-    fail "error installing dependencies"
+  then success "dependencies installed"
+  else fail "error installing dependencies"
   fi
 fi
 
